#!/bin/sh

if [ -z "${SRCROOT}" ]; then
	echo "Error: this script must be run by Xcode"
	exit 1
fi

if [ "$1" != "Cocoa" ] && [ "$1" != "SDL" ]; then
	echo "Usage: deploy_image [Cocoa|SDL]"
	exit 1
fi

TEMP_STORAGE_DIR=/Volumes/ramdisk/

if [ -e "${TEMP_STORAGE_DIR}" ]; then
	DEPLOY_IMAGE_DIR=${TEMP_STORAGE_DIR}
fi

DEPLOY_IMAGE_DIR=${DEPLOY_IMAGE_DIR}.deploy_image
DEPLOY_CONTENT_DIR=${DEPLOY_IMAGE_DIR}/.content
DEPLOY_CONTENT_EXTRAS_DIR=${DEPLOY_CONTENT_DIR}/Extras

cd "${SRCROOT}"

echo "Preparing directories..."
rm -r "${DEPLOY_IMAGE_DIR}" 2>/dev/null
mkdir -p "${DEPLOY_CONTENT_EXTRAS_DIR}"
ln -s /Applications "${DEPLOY_CONTENT_DIR}/Applications"

TARGET_BUNDLE_NAME=GZDoom.app

echo "Copying game..."
cp -R "${BUILD_DIR}/${CONFIGURATION}/GZDoom_$1.app" "${DEPLOY_CONTENT_DIR}/${TARGET_BUNDLE_NAME}"

BUNDLE_EXEC_DIR=${DEPLOY_CONTENT_DIR}/${TARGET_BUNDLE_NAME}/Contents/MacOS/

echo "Stripping executables..."
strip "${BUNDLE_EXEC_DIR}GZDoom_$1"

echo "Copying supplementary files..."
mkdir "${DEPLOY_CONTENT_EXTRAS_DIR}/Documentation"
cp -R docs/ "${DEPLOY_CONTENT_EXTRAS_DIR}/Documentation"
mkdir "${DEPLOY_CONTENT_EXTRAS_DIR}/Post-Processing Shaders"
cp -R misc/shaders/ "${DEPLOY_CONTENT_EXTRAS_DIR}/Post-Processing Shaders"
cp misc/resources/ReadMe.rtf "${DEPLOY_CONTENT_DIR}"
cp misc/resources/homepage.webloc "${DEPLOY_CONTENT_EXTRAS_DIR}/Visit GZDoom for OS X Homepage.webloc"

USER_FOLDER_CONTENTS_PATH=${DEPLOY_CONTENT_EXTRAS_DIR}"/Open GZDoom User Folder.app/Contents"
SOURCE_USER_FOLDER_PATH=misc/open_user_folder

mkdir -p "${USER_FOLDER_CONTENTS_PATH}/MacOS"
mkdir -p "${USER_FOLDER_CONTENTS_PATH}/Resources"
cp "${SOURCE_USER_FOLDER_PATH}/Info.plist" "${USER_FOLDER_CONTENTS_PATH}"
cp "${SOURCE_USER_FOLDER_PATH}/open_user_folder" "${USER_FOLDER_CONTENTS_PATH}/MacOS"
ln -s /System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/DocumentsFolderIcon.icns \
	"${USER_FOLDER_CONTENTS_PATH}/Resources/Folder.icns"

function build_image {
	DEPLOY_IMAGE_NAME=$1-`git describe`

	echo "Building $1 image..."
	hdiutil create -srcfolder "${DEPLOY_CONTENT_DIR}" -volname "${DEPLOY_IMAGE_NAME}" -format UDBZ \
		-fs HFS+ -fsargs "-c c=64,a=16,e=16" "${DEPLOY_IMAGE_DIR}/${DEPLOY_IMAGE_NAME}.dmg"
}

build_image "GZDoom"

FREEDOOM_WADS_DIR=misc/freedoom

if [ -e "${FREEDOOM_WADS_DIR}" ]; then
	echo "Copying FreeDoom files..."
	cp "${FREEDOOM_WADS_DIR}"/*.wad "${BUNDLE_EXEC_DIR}"

	build_image "FreeGZDoom"
fi
