#!/bin/sh

SOURCE_BUNDLE_NAME=GZDoom.app
BUNDLE_EXECUTABLE_PATH=Contents/MacOS/GZDoom

DEPLOY_IMAGE_DIR=.deploy_image
DEPLOY_EXTRAS_DIR=.deploy_image/Extras

cd "${SRCROOT}"

echo "Preparing directories..."
rm -r ${DEPLOY_IMAGE_DIR} 2>/dev/null
mkdir -p ${DEPLOY_EXTRAS_DIR}
ln -s /Applications ${DEPLOY_IMAGE_DIR}/Applications

echo "Copying game..."
cp -R ${BUILD_DIR}/${CONFIGURATION}_Cocoa/${SOURCE_BUNDLE_NAME} ${DEPLOY_IMAGE_DIR}

echo "Stripping executables..."
strip ${DEPLOY_IMAGE_DIR}/${SOURCE_BUNDLE_NAME}/${BUNDLE_EXECUTABLE_PATH}

echo "Copying supplementary files..."
mkdir ${DEPLOY_EXTRAS_DIR}/Documentation
cp -R docs/ ${DEPLOY_EXTRAS_DIR}/Documentation
mkdir ${DEPLOY_EXTRAS_DIR}/"Post-Processing Shaders"
cp -R misc/shaders/ ${DEPLOY_EXTRAS_DIR}/"Post-Processing Shaders"
cp misc/resources/ReadMe.rtf ${DEPLOY_IMAGE_DIR}
cp misc/resources/homepage.webloc ${DEPLOY_EXTRAS_DIR}/"Visit GZDoom for OS X Homepage.webloc"

USER_FOLDER_CONTENTS_PATH="${DEPLOY_EXTRAS_DIR}/Open GZDoom User Folder.app/Contents"
SOURCE_USER_FOLDER_PATH=misc/open_user_folder

mkdir -p "${USER_FOLDER_CONTENTS_PATH}/MacOS"
mkdir -p "${USER_FOLDER_CONTENTS_PATH}/Resources"
cp ${SOURCE_USER_FOLDER_PATH}/Info.plist "${USER_FOLDER_CONTENTS_PATH}"
cp ${SOURCE_USER_FOLDER_PATH}/open_user_folder "${USER_FOLDER_CONTENTS_PATH}/MacOS"
ln -s /System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/DocumentsFolderIcon.icns "${USER_FOLDER_CONTENTS_PATH}/Resources/Folder.icns"

echo "Building image..."
hdiutil create -srcfolder ${DEPLOY_IMAGE_DIR} -volname GZDoom -format UDBZ ${DEPLOY_IMAGE_DIR}/GZDoom.dmg
