#!/bin/sh

echo "Generating xlat_parser.c and xlat_parser.h..."

cp -f "${SRCROOT}/tools/lemon/lempar.c" "${CONFIGURATION_BUILD_DIR}/lempar.c"
	
cd "${SRCROOT}/src/xlat"
"${CONFIGURATION_BUILD_DIR}/lemon" xlat_parser.y
